### ISSUE TITLE
Crash on game launch

### ISSUE THREAD

**Issue by LoneWolfHT** [Splizard/buildacity#1]
![image](https://user-images.githubusercontent.com/28972859/147040439-48bd5674-271a-4446-a934-d9857c16e429.png)

Minetest 5.4.1, Windows

**Comment by Splizard** [comment]
Thanks for reporting, looks like this has something to do with `read("a")` perhaps needing be changed to `read("*a")`, I'm not sure why though as it has been working for me eveywhere I've tested the official builds for Windows,Linux,Android etc. Perhaps it is a Lua vs LuaJIT issue. Where did you get your copy of Minetest from?

**Comment by Splizard** [comment]
Alright I know how to fix this now, I have reproduced this crash in a bundled-lua build of Minetest, the game works fine with LuaJIT. Waiting on confirmation on whether I can still release a fix, otherwise this will get fixed January 1st and in the meantime you can use an official Minetest build (which has LuaJIT to play).

**Comment by LoneWolfHT** [comment]
You are allowed to, GreenXenith just announced
